from typing import Final


MCP_SERVER_NAME: Final[str] = "libre-box"

SESSION_INIT_COMMANDS: Final[str] = "stty -echo 2>/dev/null; export PS1=''; export PS2=''; export PROMPT_COMMAND=''; bind 'set enable-bracketed-paste off' 2>/dev/null"
SESSION_END_MARKER_PREFIX: Final[str] = "__LP_END_"
SESSION_READY_TIMEOUT_SECONDS: Final[int] = 10
SESSION_READ_INTERVAL_SECONDS: Final[float] = 0.05
SESSION_DRAIN_SECONDS: Final[float] = 0.4
SESSION_INPUT_WAIT_SECONDS: Final[float] = 2.0
SESSION_BUFFER_MAX_CHARS: Final[int] = 500000
SESSION_REAPER_INTERVAL_SECONDS: Final[float] = 60.0

BACKGROUND_LAUNCH_TIMEOUT_SECONDS: Final[int] = 15
BACKGROUND_POLL_INTERVAL_SECONDS: Final[float] = 0.5
BACKGROUND_TAIL_DEFAULT_LINES: Final[int] = 200
BACKGROUND_BYTE_COUNT_MARKER: Final[str] = "__LP_BYTES__"

SANDBOX_CONNECT_ATTEMPTS: Final[int] = 2
SANDBOX_RECONNECT_DELAY_SECONDS: Final[float] = 0.5

EXEC_TIMEOUT_KILL_GRACE_SECONDS: Final[int] = 5
EXEC_TIMEOUT_BACKSTOP_SECONDS: Final[int] = 10
EXEC_TIMEOUT_EXIT_CODE: Final[int] = 124
EXEC_KILL_EXIT_CODE: Final[int] = 137

FILE_READ_DEFAULT_LIMIT: Final[int] = 2000
FILE_READ_BINARY_SNIFF_BYTES: Final[int] = 4096
FILE_SEARCH_DEFAULT_MAX_RESULTS: Final[int] = 250
